apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        defindal/jx3-gke-gsm-dev: true
        defindal/jx3-spring: true
        defindal/xl-go-devops-training: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        defindal/jx3-gke-gsm-dev: merge
        defindal/jx3-spring: merge
        defindal/xl-go-devops-training: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - defindal/jx3-gke-gsm-dev
        - defindal/jx3-spring
        - defindal/xl-go-devops-training
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - defindal/jx3-gke-gsm-dev
        - defindal/jx3-spring
        - defindal/xl-go-devops-training
      target_url: http://lighthouse-jx.35.186.144.18.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
